### ISSUE TITLE
Only birch fletching table drops block when broken?

### ISSUE THREAD

**Issue by TheMasterBlaster** [pnk2u/More-Fletching-Tables#6]
I've noticed that only the birch fletching table drops its block when broken, all other fletching tables drop nothing. Happens on Singleplayer as well as on my Server. I have the latest versions of the mods for Minecraft version 1.21.

**Comment by pnk2u** [comment]
Sorry for this oversight and thanks for reporting it. It has been fixed in version 1.5.7 that I've just uploaded. If this fixes it, feel free to close the issue yourself or let me know if it doesn't.
