### ISSUE TITLE
Villagers only get jobs from birch fletching tables

### ISSUE THREAD

**Issue by santastolle** [pnk2u/More-Fletching-Tables#7]
v1.6.0
MC v1.21

Villagers only get jobs from birch fletching tables.

**Comment by pnk2u** [comment]
Thanks for reporting this, unfortunately I cannot reproduce it on my side, what other mods did you have installed when this happened?

**Comment by santastolle** [comment]
Thanks for the quick response! The culprit was Visual Workbench. For some reason it recognizes the fletching tables as crafting tables. The birch fletching table works fine.

**Comment by pnk2u** [comment]
Ah, I see, thanks for finding that out for me, much appreciated, it should then be fixed in version 1.6.1.

**Comment by santastolle** [comment]
You are an absolute legend. Cheers!
